# Generated by Django 2.2.5 on 2019-09-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbot', '0016_postrevision_ip_addr'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='translate_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
