# Generated by Django 2.2.5 on 2019-09-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbot', '0017_post_translate_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bch_address',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
