# Generated by Django 2.2.5 on 2019-09-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbot', '0018_userprofile_bch_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='translate_from',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='translate_to',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
