# Generated by Django 2.2.5 on 2019-09-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbot', '0019_auto_20190920_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
