# Generated by Django 2.2.5 on 2019-09-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbot', '0020_auto_20190921_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='postrevision',
            name='translate_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
