# Generated by Django 2.2.5 on 2019-10-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbot', '0021_postrevision_translate_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='translation_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
