# Generated by Django 2.2.5 on 2019-10-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbot', '0022_post_translation_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='translation_budget_currency',
            field=models.CharField(blank=True, choices=[('usd', 'USD'), ('eur', 'EUR')], max_length=4, null=True),
        ),
    ]
