# Generated by Django 2.2.5 on 2019-11-11 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('askbot', '0023_post_translation_budget_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('duration', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('offer_made', 'Offer Made'), ('offer_accepted', 'Offer Accepted'), ('offer_denied', 'Offer Denied'), ('escrow_funded', 'Escrow Funded'), ('escrow_released', 'Escrow Released'), ('dispute', 'Dispute'), ('escrow_released_by_judge', 'Escrow Released By Judge')], max_length=25)),
                ('amount', models.PositiveIntegerField()),
                ('employer_pub_key', models.CharField(max_length=67)),
                ('employee_pub_key', models.CharField(blank=True, max_length=67, null=True)),
                ('employer_priv_key', models.TextField(blank=True, null=True)),
                ('judge_pub_key', models.CharField(max_length=67)),
                ('escrow_address', models.CharField(blank=True, max_length=55, null=True)),
                ('judgeSignature', models.TextField(blank=True, null=True)),
                ('fee_taken', models.BooleanField(default=False)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_made', to=settings.AUTH_USER_MODEL)),
                ('taker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_accepted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
