# Generated by Django 2.2.5 on 2019-11-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbot', '0024_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='employee_priv_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='employer_priv_key',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
