# Generated by Django 2.2.5 on 2019-11-16 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('askbot', '0026_contract_accept_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='dispute_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='dispute_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disputes_won', to=settings.AUTH_USER_MODEL),
        ),
    ]
