# Generated by Django 2.2.5 on 2019-11-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbot', '0027_auto_20191116_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='dispute_text',
            new_name='dispute_complain',
        ),
        migrations.AddField(
            model_name='contract',
            name='judge_dispute_rule',
            field=models.TextField(blank=True, null=True),
        ),
    ]
