# Generated by Django 2.2.5 on 2019-11-18 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askbot', '0028_auto_20191116_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='accept_offer',
        ),
    ]
