# Generated by Django 2.2.5 on 2019-11-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbot', '0029_remove_contract_accept_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='accepted_offer',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
            preserve_default=False,
        ),
    ]
