# Generated by Django 2.2.5 on 2019-11-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbot', '0030_contract_accepted_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='accepted_offer',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='Accept Offer'),
        ),
    ]
