# Generated by Django 2.2.5 on 2019-11-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbot', '0031_auto_20191118_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='state',
            field=models.CharField(choices=[('offer_made', 'Offer Made'), ('offer_accepted', 'Offer Accepted'), ('offer_denied', 'Offer Denied'), ('escrow_funded', 'Escrow Funded'), ('escrow_released', 'Escrow Released'), ('dispute', 'Dispute'), ('escrow_released_by_judge', 'Escrow Released By Judge')], default='offer_made', max_length=25),
        ),
    ]
