# Generated by Django 2.2.5 on 2019-11-22 05:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbot', '0033_contract_offer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='dispute_evidence',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'rar'])]),
        ),
    ]
