# Generated by Django 2.2.5 on 2019-11-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbot', '0034_contract_dispute_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_title',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
