# Generated by Django 2.2.5 on 2019-11-26 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('askbot', '0035_contract_contract_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='user_whom_released_escrow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escrows_released', to=settings.AUTH_USER_MODEL),
        ),
    ]
