# Generated by Django 2.2.5 on 2019-12-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbot', '0036_contract_user_whom_released_escrow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='post',
            name='priv_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='pub_key',
            field=models.CharField(blank=True, max_length=67, null=True),
        ),
    ]
