# Generated by Django 2.2.5 on 2019-12-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbot', '0037_auto_20191206_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
