# Generated by Django 2.2.5 on 2019-12-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbot', '0039_auto_20191209_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='state',
            field=models.CharField(choices=[('offer_made', 'Offer Made'), ('offer_denied', 'Offer Denied'), ('escrow_funded', 'Escrow Funded'), ('escrow_released', 'Escrow Released'), ('dispute', 'Dispute'), ('escrow_released_by_judge', 'Escrow Released By Judge')], default='offer_made', max_length=25),
        ),
    ]
