# Generated by Django 2.2.5 on 2019-12-13 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askbot', '0040_auto_20191209_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='offer_text',
        ),
    ]
