# Generated by Django 2.2.5 on 2019-12-13 02:48

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbot', '0042_auto_20191213_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0006'))]),
        ),
    ]
